"""create alerts table

Revision ID: 11917b071ce0
Revises: ffdebe73ab8b
Create Date: 2026-07-22 10:13:45.667090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11917b071ce0'
down_revision: Union[str, Sequence[str], None] = 'ffdebe73ab8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('metric', sa.Enum('LATENCY_AVG', 'LATENCY_MAX', 'ERROR_RATE', 'TIMEOUT_RATE', 'COST', 'TOTAL_TOKENS', name='alertmetric'), nullable=False),
    sa.Column('operator', sa.Enum('GREATER_THAN', 'GREATER_THAN_EQUAL', 'LESS_THAN', 'LESS_THAN_EQUAL', name='alertoperator'), nullable=False),
    sa.Column('threshold_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('window_minutes', sa.Enum('FIVE', 'FIFTEEN', 'THIRTY', 'SIXTY', 'ONE_TWENTY', name='alertwindow'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
