"""added integer in win minutes”

Revision ID: 571fb1102d16
Revises: 078101d3e1fe
Create Date: 2026-08-17 10:28:45.944265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '571fb1102d16'
down_revision: Union[str, Sequence[str], None] = '078101d3e1fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
        ALTER TABLE alerts
        ALTER COLUMN window_minutes TYPE TEXT
        USING window_minutes::TEXT
    """)

    op.execute("""
        UPDATE alerts
        SET window_minutes = CASE window_minutes
            WHEN 'FIVE' THEN '5'
            WHEN 'FIFTEEN' THEN '15'
            WHEN 'THIRTY' THEN '30'
            WHEN 'SIXTY' THEN '60'
            WHEN 'ONE_TWENTY' THEN '120'
            ELSE window_minutes
        END
    """)

    op.execute("""
        ALTER TABLE alerts
        ALTER COLUMN window_minutes TYPE INTEGER
        USING window_minutes::INTEGER
    """)

    op.execute("""
        DROP TYPE IF EXISTS alertwindow
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alerts', 'window_minutes',
               existing_type=sa.Integer(),
               type_=postgresql.ENUM('FIVE', 'FIFTEEN', 'THIRTY', 'SIXTY', 'ONE_TWENTY', name='alertwindow'),
               existing_nullable=False)
    # ### end Alembic commands ###
