"""create usage_limits table

Revision ID: 7745af257650
Revises: 11917b071ce0
Create Date: 2026-08-01 10:47:01.414280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7745af257650'
down_revision: Union[str, Sequence[str], None] = '11917b071ce0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('max_requests_per_minute', sa.Integer(), nullable=True),
    sa.Column('max_requests_per_hour', sa.Integer(), nullable=True),
    sa.Column('max_requests_per_day', sa.Integer(), nullable=True),
    sa.Column('max_input_tokens_per_day', sa.Integer(), nullable=True),
    sa.Column('max_output_tokens_per_day', sa.Integer(), nullable=True),
    sa.Column('max_cost_per_day', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('block_on_limit', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_limits_id'), 'usage_limits', ['id'], unique=False)
    op.create_index(op.f('ix_usage_limits_user_id'), 'usage_limits', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_limits_user_id'), table_name='usage_limits')
    op.drop_index(op.f('ix_usage_limits_id'), table_name='usage_limits')
    op.drop_table('usage_limits')
    # ### end Alembic commands ###
